/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RadioButton } from "./components/ui-radio-group/types";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface UiRadioButton {
        /**
          * Radiobutton ID
         */
        "id": string;
        /**
          * Radiobutton value
         */
        "isChecked"?: boolean;
        /**
          * Radiobutton label
         */
        "label"?: string;
        /**
          * Radiobutton name
         */
        "name": string;
        /**
          * Radiobutton value
         */
        "value": string;
    }
    interface UiRadioGroup {
        /**
          * Radio button items
         */
        "items": RadioButton[];
        /**
          * Radio group name
         */
        "name": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLUiRadioButtonElement extends Components.UiRadioButton, HTMLStencilElement {
    }
    var HTMLUiRadioButtonElement: {
        prototype: HTMLUiRadioButtonElement;
        new (): HTMLUiRadioButtonElement;
    };
    interface HTMLUiRadioGroupElement extends Components.UiRadioGroup, HTMLStencilElement {
    }
    var HTMLUiRadioGroupElement: {
        prototype: HTMLUiRadioGroupElement;
        new (): HTMLUiRadioGroupElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "ui-radio-button": HTMLUiRadioButtonElement;
        "ui-radio-group": HTMLUiRadioGroupElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface UiRadioButton {
        /**
          * Radiobutton ID
         */
        "id"?: string;
        /**
          * Radiobutton value
         */
        "isChecked"?: boolean;
        /**
          * Radiobutton label
         */
        "label"?: string;
        /**
          * Radiobutton name
         */
        "name"?: string;
        "onChangeRadio"?: (event: CustomEvent<unknown>) => void;
        /**
          * Radiobutton value
         */
        "value"?: string;
    }
    interface UiRadioGroup {
        /**
          * Radio button items
         */
        "items"?: RadioButton[];
        /**
          * Radio group name
         */
        "name"?: string;
        "onChangeValue"?: (event: CustomEvent<unknown>) => void;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "ui-radio-button": UiRadioButton;
        "ui-radio-group": UiRadioGroup;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "ui-radio-button": LocalJSX.UiRadioButton & JSXBase.HTMLAttributes<HTMLUiRadioButtonElement>;
            "ui-radio-group": LocalJSX.UiRadioGroup & JSXBase.HTMLAttributes<HTMLUiRadioGroupElement>;
        }
    }
}
